import { normalizeSupportNeeds } from "./matching.js?v=3607856";

const STORAGE_KEY = "raise_local_platform_v2";

export const DEMO_DATA = {
  campaignRequests: [
    {
      id: "request-fresh-start",
      organizationName: "Fresh Start Pantry",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Maya Thompson",
      email: "demo-nonprofit@raiselocal.example",
      phone: "555-0198",
      website: "https://freshstartpantry.org",
      socialLinks: "Instagram: @freshstartpantry",
      classification: "501(c)(3)",
      communitiesServed: "Brooklyn families and school communities",
      mission: "Reduce weekend food insecurity for families with school-aged children.",
      audienceServed: "Families, parents, volunteers, and local donors",
      audienceSize: 850,
      campaignDescription: "Stock weekend meal bags for families during the fall school term.",
      fundingGoal: 5000,
      expectedParticipation: 120,
      minimumSize: 80,
      idealSize: 120,
      startDate: "2026-09-15",
      endDate: "2026-10-15",
      partnershipDeadline: "2026-09-10",
      causeArea: "Food access",
      businessPreference: "Food and beverage",
      preferredCategories: ["Food and beverage", "Restaurant", "Beverage"],
      eventType: "Food-based fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Percentage of sales campaign", "Product donation"],
      supportNeeds: ["Food & beverage", "Products or corporate gifting"],
      geography: "Brooklyn",
      mustHaves: "Brooklyn service area, food-based support, capacity for at least 80 orders.",
      niceToHaves: "Pickup option and a recognizable local brand.",
      priorFundraiser: "Yes - local restaurant night",
      status: "new",
    },
    {
      id: "request-grove-park",
      organizationName: "Grove Park Foundation",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Gavin McGuire",
      email: "contact@groveparkfoundation.org",
      website: "https://groveparkfoundation.org/",
      socialLinks: "",
      mission: "Revitalize Atlanta's Grove Park neighborhood by working with local partners, leaders, and residents to create a healthy, equitable, and vibrant community.",
      communitiesServed: "Grove Park residents, families, students, and local businesses",
      campaignDescription: "Build support for neighborhood economic mobility, education, and community wellness initiatives.",
      fundingGoal: 10000,
      expectedParticipation: 150,
      minimumSize: 50,
      idealSize: 150,
      startDate: "2026-10-01",
      endDate: "2026-12-15",
      partnershipDeadline: "2026-09-20",
      causeArea: "Community",
      businessPreference: "No preference",
      preferredCategories: ["Services", "Retail", "Food and beverage"],
      eventType: "Community event",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Event activation"],
      supportNeeds: ["Corporate sponsorship", "Professional services", "Event activation"],
      geography: "Atlanta, GA",
      mustHaves: "A partner committed to equitable neighborhood investment and measurable community impact.",
      niceToHaves: "Employee engagement, event participation, and a multi-month relationship.",
      priorFundraiser: "Yes - with local partners",
      campaignStage: "submitted",
      createdAt: "2026-09-18T12:00:00.000Z",
      successDetails: "",
      status: "new",
    },
    {
      id: "request-unity-now",
      organizationName: "UNITYNow",
      organizationType: "501(c)(3) nonprofit",
      contactName: "UNITYNow Team",
      email: "info@unitynow.org",
      phone: "202-236-7221",
      website: "https://www.unitynow.org/",
      socialLinks: "",
      mission: "Serve, advocate, educate, and advance culture in historically overlooked communities by bridging the gap between inequality and unity.",
      communitiesServed: "Youth, families, and historically overlooked communities across the DMV",
      campaignDescription: "Raise support for education, community service, advocacy, and leadership pathways.",
      fundingGoal: 7500,
      expectedParticipation: 125,
      minimumSize: 50,
      idealSize: 125,
      startDate: "2026-10-15",
      endDate: "2026-12-31",
      partnershipDeadline: "2026-10-01",
      causeArea: "Education",
      businessPreference: "No preference",
      preferredCategories: ["Services", "Retail", "Local media"],
      eventType: "Community event",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Corporate sponsorship"],
      supportNeeds: ["Corporate sponsorship", "Professional services", "Event activation"],
      geography: "DMV / Northern Virginia",
      mustHaves: "A partner aligned with equity, education, and measurable community impact.",
      niceToHaves: "Volunteer participation, sponsorship support, and cultural programming.",
      priorFundraiser: "Yes - with local partners",
      campaignStage: "submitted",
      createdAt: "2026-09-18T12:30:00.000Z",
      successDetails: "",
      status: "new",
    },
    {
      id: "request-art-room",
      organizationName: "PS 118 Art Room",
      organizationType: "School / PTA",
      contactName: "Jordan Lee",
      email: "jordan@example.edu",
      phone: "555-0142",
      website: "https://ps118.example.edu",
      socialLinks: "Instagram: @ps118artroom",
      classification: "School / PTA",
      communitiesServed: "Queens students, parents, teachers, and neighborhood donors",
      mission: "Expand access to creative enrichment and student art showcases.",
      audienceServed: "Students, parents, teachers, and alumni",
      audienceSize: 600,
      campaignDescription: "Raise money for after-school art supplies and student showcase materials.",
      fundingGoal: 3500,
      expectedParticipation: 90,
      minimumSize: 50,
      idealSize: 90,
      startDate: "2026-10-01",
      endDate: "2026-10-31",
      partnershipDeadline: "2026-09-24",
      causeArea: "Arts",
      businessPreference: "Retail",
      preferredCategories: ["Retail", "Local media"],
      eventType: "Product fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Product donation"],
      supportNeeds: ["Products or corporate gifting", "Corporate sponsorship"],
      geography: "Queens",
      mustHaves: "Queens service area and product or sponsorship support.",
      niceToHaves: "School-friendly business and flexible campaign dates.",
      priorFundraiser: "No",
      status: "new",
    },
    {
      id: "request-young-excellence",
      organizationName: "Young Excellence Society",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Program Director",
      email: "demo-nonprofit-2@raiselocal.example",
      phone: "555-0177",
      website: "https://www.youngexcellencesociety.org/",
      socialLinks: "Instagram: @yesacademyus",
      classification: "501(c)(3)",
      communitiesServed: "At-risk and inner-city youth ages 4-18 across all five NYC boroughs, based in Harlem",
      mission: "A Harlem-based community center meeting the educational, developmental, recreational, and career needs of inner-city and at-risk youth through year-round After School and Summer Camp programs.",
      audienceServed: "Youth ages 4-18, families, mentors, and community donors",
      audienceSize: 400,
      campaignDescription: "Fund a fall after-school cohort and enrichment programming for Harlem youth.",
      fundingGoal: 4000,
      expectedParticipation: 100,
      minimumSize: 60,
      idealSize: 100,
      startDate: "2026-09-20",
      endDate: "2026-11-20",
      partnershipDeadline: "2026-09-15",
      causeArea: "Education",
      businessPreference: "Food and beverage",
      preferredCategories: ["Food and beverage"],
      eventType: "Food-based fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Percentage of sales campaign"],
      supportNeeds: ["Food & beverage", "Products or corporate gifting"],
      geography: "Manhattan",
      mustHaves: "Manhattan (Harlem) service area, youth/education-focused partner, capacity for at least 60 participants.",
      niceToHaves: "Multi-month partnership and social media cross-promotion.",
      priorFundraiser: "No",
      status: "new",
    },
  ],
  businesses: [
    {
      id: "biz-yamaas",
      name: "Yamaas Olive Oil & Vinegar",
      website: "https://yamaasoliveoil.example",
      socialLinks: "Instagram: @yamaasoliveoil",
      contactName: "Yara Massoud",
      email: "demo-business@raiselocal.example",
      phone: "555-0130",
      category: "Food and beverage",
      businessGoals: ["New customers", "Product trial", "Community visibility", "CSR/community impact"],
      serviceAreas: ["Brooklyn", "Queens", "New York"],
      fulfillmentScope: "Local",
      causeAreas: ["Food access", "Community", "Health"],
      contributionTypes: ["Product donation", "Percent of sales", "Event hosting"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Hosted event", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Venue space"],
      productsServices: "Olive oil sets, tasting kits, hosted sampling events, and gift bundles.",
      averagePriceRange: "$18-$65",
      minimumOrderRequirement: 500,
      minimumCapacity: 50,
      maximumCapacity: 250,
      idealEventSize: 125,
      campaignCap: 3,
      activeCampaigns: 1,
      estimatedUnitContribution: 20,
      availableFrom: "2026-09-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "Founding business. Strong fit for food, wellness, and community campaigns.",
      rating: 4.8,
      reviewNote: "Reliable partner for community food campaigns.",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-eyeland-vibes",
      name: "Eyeland Vibes",
      website: "https://eyelandvibes.org",
      socialLinks: "Instagram: @eyelandvibesorg",
      contactName: "Eyeland Vibes Team",
      email: "hello@eyelandvibes.org",
      category: "Retail",
      businessGoals: ["Brand awareness", "Community visibility", "CSR/community impact"],
      serviceAreas: ["National", "New York", "DMV"],
      fulfillmentScope: "National",
      causeAreas: ["Health", "Community", "Youth"],
      contributionTypes: ["Percent of sales", "Product donation", "Sponsorship dollars"],
      partnershipTypes: ["Fundraising", "Event sponsorship", "Product donation"],
      offerTypes: ["Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Fashion eyewear and blue-light glasses, typically priced from $25 to $38.",
      averagePriceRange: "$25-$38",
      minimumOrderRequirement: 25,
      minimumCapacity: 25,
      maximumCapacity: 250,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 8,
      availableFrom: "2026-09-15",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Shipping", "Delivery", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Eyewear brand rooted in Trinidadian culture and self-expression that supports global eye-care initiatives.",
      rating: null,
      reviewNote: "",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-first-choice-brew",
      name: "First Choice Brew",
      website: "https://www.firstchoicebrew.com/",
      socialLinks: "",
      contactName: "First Choice Brew Team",
      email: "info@firstchoicebrew.com",
      category: "Beverage",
      businessGoals: ["New customers", "Brand awareness", "Long-term nonprofit partnerships"],
      serviceAreas: ["New York", "National"],
      fulfillmentScope: "National",
      causeAreas: ["Community", "Education", "Workforce development"],
      contributionTypes: ["Percent of sales", "Product donation", "Event hosting"],
      partnershipTypes: ["Fundraising", "Hosted event", "Product donation", "Event sponsorship"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Single-origin Colombian coffee beans and grounds, subscriptions, office programs, and wholesale coffee.",
      averagePriceRange: "$15-$60",
      minimumOrderRequirement: 25,
      minimumCapacity: 25,
      maximumCapacity: 300,
      idealEventSize: 100,
      campaignCap: 3,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-09-15",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Shipping", "Delivery", "Pickup"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "New York specialty coffee brand sourcing from women-led and youth-operated farms in Medellin.",
      rating: null,
      reviewNote: "",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-sofia-grace",
      name: "Sofia & Grace",
      website: "https://sofiaandgrace.example",
      socialLinks: "Instagram: @sofiaandgrace",
      contactName: "Sofia Reyes",
      email: "hello@sofiaandgrace.example",
      phone: "555-0131",
      category: "Food and beverage",
      businessGoals: ["Foot traffic", "Brand awareness", "Social media exposure", "Long-term nonprofit partnerships"],
      serviceAreas: ["Brooklyn", "Manhattan"],
      fulfillmentScope: "Local",
      causeAreas: ["Youth", "Food access", "Education"],
      contributionTypes: ["Product donation", "Percent of sales"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting"],
      productsServices: "Cookie boxes, dessert trays, seasonal fundraiser bundles, and pickup campaigns.",
      averagePriceRange: "$24-$48",
      minimumOrderRequirement: 300,
      minimumCapacity: 30,
      maximumCapacity: 180,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-09-10",
      availableTo: "2026-11-30",
      fulfillmentOptions: ["Pickup", "Delivery"],
      leadTimeDays: 10,
      orgTypesSupported: ["School / PTA", "501(c)(3) nonprofit"],
      notes: "Founding business. Cookie shop interview validated appetite for local cause partnerships.",
      rating: 4.6,
      reviewNote: "Warm brand fit for school and youth campaigns.",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-paper-porch",
      name: "Paper Porch Goods",
      website: "https://paperporchgoods.example",
      socialLinks: "Instagram: @paperporchgoods",
      contactName: "Priya Osei",
      email: "hello@paperporchgoods.example",
      phone: "555-0132",
      category: "Retail",
      businessGoals: ["Community visibility", "Email/newsletter exposure", "Content opportunities", "Local press"],
      serviceAreas: ["Queens", "Brooklyn"],
      fulfillmentScope: "Regional",
      causeAreas: ["Arts", "Education", "Community"],
      contributionTypes: ["Percent of sales", "Sponsorship dollars"],
      partnershipTypes: ["Fundraising", "Event sponsorship", "Product donation"],
      offerTypes: ["Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Stationery bundles, classroom supply packs, raffle prizes, and sponsor dollars.",
      averagePriceRange: "$12-$40",
      minimumOrderRequirement: 250,
      minimumCapacity: 40,
      maximumCapacity: 120,
      idealEventSize: 80,
      campaignCap: 1,
      activeCampaigns: 0,
      estimatedUnitContribution: 15,
      availableFrom: "2026-09-20",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 7,
      orgTypesSupported: ["School / PTA", "Community organization", "501(c)(3) nonprofit"],
      notes: "Good fit for school, arts, and neighborhood campaigns.",
      rating: 4.2,
      reviewNote: "Strong for small product fundraisers and school campaigns.",
      unavailable: false,
      status: "ready",
    },
  ],
  matches: [],
  notifications: [],
};

export function loadData() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return structuredClone(DEMO_DATA);
  try {
    const parsed = JSON.parse(raw);
    // Upgrades old partner-type labels (see LEGACY_SUPPORT_NEEDS in
    // matching.js) on read, non-destructively, so previously saved answers
    // keep matching instead of silently failing a string-overlap comparison.
    const campaignRequests = (Array.isArray(parsed.campaignRequests) ? parsed.campaignRequests : []).map((r) => ({
        rating: null,
        reviewNote: "",
        ...r,
        supportNeeds: normalizeSupportNeeds(r.supportNeeds),
      }));
    const businesses = (Array.isArray(parsed.businesses) ? parsed.businesses : []).map((b) => ({
        ...b,
        offerTypes: normalizeSupportNeeds(b.offerTypes),
      }));
    const existingRequestIds = new Set(campaignRequests.map((record) => record.id));
    const existingBusinessIds = new Set(businesses.map((record) => record.id));
    return {
      campaignRequests: [...campaignRequests, ...DEMO_DATA.campaignRequests.filter((record) => !existingRequestIds.has(record.id))],
      businesses: [...businesses, ...DEMO_DATA.businesses.filter((record) => !existingBusinessIds.has(record.id))],
      matches: Array.isArray(parsed.matches) ? parsed.matches : [],
      notifications: Array.isArray(parsed.notifications) ? parsed.notifications : [],
    };
  } catch {
    return structuredClone(DEMO_DATA);
  }
}

export function saveData(data) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}

export function resetDemoData() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(DEMO_DATA));
  return loadData();
}
