import { normalizeSupportNeeds } from "./matching.js?v=3607856";

const STORAGE_KEY = "raise_local_platform_v5";

export function emptyData() {
  return { campaignRequests: [], businesses: [], matches: [], notifications: [] };
}

export const DEMO_DATA = {
  campaignRequests: [
    {
      id: "request-grove-park",
      organizationName: "Grove Park Foundation",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Gavin McGuire",
      email: "contact@groveparkfoundation.org",
      website: "https://groveparkfoundation.org/",
      socialLinks: "",
      mission: "Revitalize Atlanta's Grove Park neighborhood by working with local partners, leaders, and residents to create a healthy, equitable, and vibrant community.",
      communitiesServed: "Grove Park residents, families, students, and local businesses",
      campaignDescription: "Build support for neighborhood economic mobility, education, and community wellness initiatives.",
      fundingGoal: 10000,
      expectedParticipation: 150,
      minimumSize: 50,
      idealSize: 150,
      startDate: "2026-10-01",
      endDate: "2026-12-15",
      partnershipDeadline: "2026-09-20",
      causeArea: "Community",
      businessPreference: "No preference",
      preferredCategories: ["Services", "Retail", "Food and beverage", "Wellness"],
      eventType: "Community event",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Event activation"],
      supportNeeds: ["Corporate sponsorship", "Professional services", "Event activation"],
      geography: "Atlanta, GA",
      mustHaves: "A partner committed to equitable neighborhood investment and measurable community impact.",
      niceToHaves: "Employee engagement, event participation, and a multi-month relationship.",
      priorFundraiser: "Yes - with local partners",
      campaignStage: "submitted",
      createdAt: "2026-09-18T12:00:00.000Z",
      successDetails: "",
      status: "new",
    },
    {
      id: "request-unity-now",
      organizationName: "UNITYNow",
      organizationType: "501(c)(3) nonprofit",
      contactName: "UNITYNow Team",
      email: "info@unitynow.org",
      phone: "202-236-7221",
      website: "https://www.unitynow.org/",
      socialLinks: "",
      mission: "Serve, advocate, educate, and advance culture in historically overlooked communities by bridging the gap between inequality and unity.",
      communitiesServed: "Youth, families, and historically overlooked communities across the DMV",
      campaignDescription: "Raise support for education, community service, advocacy, and leadership pathways.",
      fundingGoal: 7500,
      expectedParticipation: 125,
      minimumSize: 50,
      idealSize: 125,
      startDate: "2026-10-15",
      endDate: "2026-12-31",
      partnershipDeadline: "2026-10-01",
      causeArea: "Education",
      businessPreference: "No preference",
      preferredCategories: ["Services", "Retail", "Local media"],
      eventType: "Community event",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Corporate sponsorship"],
      supportNeeds: ["Corporate sponsorship", "Professional services", "Event activation"],
      geography: "DMV / Northern Virginia",
      mustHaves: "A partner aligned with equity, education, and measurable community impact.",
      niceToHaves: "Volunteer participation, sponsorship support, and cultural programming.",
      priorFundraiser: "Yes - with local partners",
      campaignStage: "submitted",
      createdAt: "2026-09-18T12:30:00.000Z",
      successDetails: "",
      status: "new",
    },
    {
      id: "request-young-excellence",
      organizationName: "YES Academy Inc.",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Program Director",
      email: "info@youngexcellencesociety.org",
      phone: "513-HARLEM1",
      website: "https://www.youngexcellencesociety.org/",
      socialLinks: "Instagram: @yesacademyus",
      classification: "501(c)(3)",
      communitiesServed: "Harlem youth, families, mentors, and community donors",
      mission: "Support Harlem youth through education, enrichment, and community programs.",
      audienceServed: "Youth ages 4-18, families, mentors, and community donors",
      audienceSize: 400,
      campaignDescription: "Cookies for the Toy Drive: a share of holiday cookie sales funds YES Academy's Harlem Care Toy Drive.",
      fundingGoal: 4000,
      expectedParticipation: 100,
      minimumSize: 60,
      idealSize: 100,
      startDate: "2026-09-20",
      endDate: "2026-11-20",
      partnershipDeadline: "2026-09-15",
      causeArea: "Youth",
      businessPreference: "Food and beverage",
      preferredCategories: ["Food and beverage"],
      eventType: "Food-based fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Percentage of sales campaign"],
      supportNeeds: ["Food & beverage", "Products or corporate gifting"],
      geography: "Manhattan",
      mustHaves: "Manhattan (Harlem) service area, youth-focused partner, capacity for at least 60 participants.",
      niceToHaves: "A warm local brand, seasonal campaign energy, and social media cross-promotion.",
      priorFundraiser: "No",
      status: "new",
    },
  ],
  businesses: [
    {
      id: "biz-yamaas",
      name: "Yamaas Olive Oil & Vinegar",
      website: "https://yamaas.com/",
      socialLinks: "Instagram: @yamaasoliveoil",
      contactName: "Outreach lead to confirm",
      email: "info@yamaas.com",
      phone: "202-841-2043",
      category: "Food and beverage",
      businessGoals: ["New customers", "Product trial", "Community visibility", "CSR/community impact"],
      serviceAreas: ["Brooklyn", "Queens", "New York"],
      fulfillmentScope: "Local",
      causeAreas: ["Food access", "Community", "Health"],
      contributionTypes: ["Product donation", "Percent of sales", "Event hosting"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Hosted event", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Venue space"],
      productsServices: "Olive oil sets, tasting kits, hosted sampling events, and gift bundles.",
      averagePriceRange: "$18-$65",
      minimumOrderRequirement: 500,
      minimumCapacity: 50,
      maximumCapacity: 250,
      idealEventSize: 125,
      campaignCap: 3,
      activeCampaigns: 1,
      estimatedUnitContribution: 20,
      availableFrom: "2026-09-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "Founding business. Public website lists YAMAAS! as a premium olive oil and balsamic vinegar business; confirm current campaign participation before introduction.",
      rating: 4.8,
      reviewNote: "Reliable partner for community food campaigns.",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-eyeland-vibes",
      name: "Eyeland Vibes",
      website: "https://eyelandvibes.org",
      socialLinks: "Instagram: @eyelandvibesorg",
      contactName: "Eyeland Vibes Team",
      email: "hello@eyelandvibes.org",
      category: "Retail",
      businessGoals: ["Brand awareness", "Community visibility", "CSR/community impact"],
      serviceAreas: ["National", "New York", "DMV"],
      fulfillmentScope: "National",
      causeAreas: ["Health", "Community", "Youth"],
      contributionTypes: ["Percent of sales", "Product donation", "Sponsorship dollars"],
      partnershipTypes: ["Fundraising", "Event sponsorship", "Product donation"],
      offerTypes: ["Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Fashion eyewear and blue-light glasses, typically priced from $25 to $38.",
      averagePriceRange: "$25-$38",
      minimumOrderRequirement: 25,
      minimumCapacity: 25,
      maximumCapacity: 250,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 8,
      availableFrom: "2026-09-15",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Shipping", "Delivery", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Eyewear brand rooted in Trinidadian culture and self-expression that supports global eye-care initiatives.",
      rating: null,
      reviewNote: "",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-first-choice-brew",
      name: "First Choice Brew",
      website: "https://www.firstchoicebrew.com/",
      socialLinks: "",
      contactName: "First Choice Brew Team",
      email: "info@firstchoicebrew.com",
      category: "Beverage",
      businessGoals: ["New customers", "Brand awareness", "Long-term nonprofit partnerships"],
      serviceAreas: ["New York", "National"],
      fulfillmentScope: "National",
      causeAreas: ["Community", "Education", "Workforce development"],
      contributionTypes: ["Percent of sales", "Product donation", "Event hosting"],
      partnershipTypes: ["Fundraising", "Hosted event", "Product donation", "Event sponsorship"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Single-origin Colombian coffee beans and grounds, subscriptions, office programs, and wholesale coffee.",
      averagePriceRange: "$15-$60",
      minimumOrderRequirement: 25,
      minimumCapacity: 25,
      maximumCapacity: 300,
      idealEventSize: 100,
      campaignCap: 3,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-09-15",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Shipping", "Delivery", "Pickup"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "New York specialty coffee brand sourcing from women-led and youth-operated farms in Medellin.",
      rating: null,
      reviewNote: "",
      unavailable: false,
      status: "ready",
    },
    {
      id: "business-fe9b3739-59c6-411d-b1df-c8222bf888ca",
      name: "Candle Light Care Home Health Services",
      website: "https://bizstanding.com/directory/TX/CA/2147/",
      socialLinks: "",
      contactName: "Outreach lead to confirm",
      email: "",
      phone: "Outreach needed",
      category: "Services",
      businessGoals: ["Community visibility", "CSR/community impact", "Long-term nonprofit partnerships"],
      serviceAreas: ["Rockwall, TX", "Dallas-Fort Worth", "Texas"],
      fulfillmentScope: "Local",
      causeAreas: ["Health", "Community", "Caregiving"],
      contributionTypes: ["Sponsorship dollars", "Event sponsorship", "Professional services"],
      partnershipTypes: ["Event sponsorship", "Fundraising", "Event activation"],
      offerTypes: ["Professional services", "Corporate sponsorship"],
      productsServices: "Home health / allied services lead. Public registry-style listing identifies Candle Light Care Home Health Services Limited Liability Company in Rockwall, Texas.",
      averagePriceRange: "Outreach needed",
      pricingPoint: "Outreach needed",
      minimumOrderRequirement: 0,
      minimumCapacity: 10,
      maximumCapacity: 100,
      idealEventSize: 50,
      campaignCap: 1,
      activeCampaigns: 0,
      estimatedUnitContribution: 0,
      availabilityPreference: "Outreach needed",
      fulfillmentOptions: ["In person"],
      leadTimeDays: 21,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Restored real business lead. Public Texas business-directory record lists Candle Light Care Home Health Services Limited Liability Company at 3919 Poplar Point Dr, Rockwall, TX 75032. Not confirmed as a Raise Local participant; outreach is required before any introduction.",
      rating: null,
      reviewNote: "Real lead restored after removing old test contact data. Use as health/community services lead research, not as a confirmed partner.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public business-directory record; not registered in Raise Local yet",
      sourceUrl: "https://bizstanding.com/directory/TX/CA/2147/",
    },
    {
      id: "biz-paco-tacos-atl",
      name: "Paco Tacos ATL (Potential Lead)",
      website: "https://www.restaurantji.com/ga/atlanta/paco-tacos-atl-/",
      socialLinks: "Instagram: @pacotacosatl",
      contactName: "Outreach lead to confirm",
      email: "",
      phone: "404-796-9951",
      category: "Food and beverage",
      businessGoals: ["Foot traffic", "Community visibility", "Brand awareness", "CSR/community impact"],
      serviceAreas: ["Grove Park", "Atlanta, GA", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Community", "Food access", "Youth"],
      contributionTypes: ["Percent of sales", "Event hosting", "Product donation"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Hosted event", "Event activation"],
      offerTypes: ["Food & beverage", "Event activation"],
      productsServices: "Mexican street food, community food activation, possible restaurant fundraiser day, catering, or neighborhood pickup campaign.",
      averagePriceRange: "$9-$18",
      minimumOrderRequirement: 250,
      minimumCapacity: 40,
      maximumCapacity: 220,
      idealEventSize: 125,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 10,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business listing, but the business is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "Public listings place Paco Tacos ATL at 2222 Donald Lee Hollowell Pkwy NW in Atlanta/Grove Park. Food and beverage fit for a neighborhood fundraiser, pickup campaign, or event activation.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus public restaurant listings; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Paco%20Tacos%20ATL%202222%20Donald%20Lee%20Hollowell%20Pkwy%20NW%20Atlanta%20GA%2030318",
      sourceUrl: "https://www.restaurantji.com/ga/atlanta/paco-tacos-atl-/",
    },
    {
      id: "biz-casa-de-luz",
      name: "Casa de Luz (Potential Lead)",
      website: "https://casadeluzatl.com/",
      socialLinks: "",
      contactName: "Outreach lead to confirm",
      email: "",
      phone: "Outreach needed",
      category: "Wellness",
      businessGoals: ["CSR/community impact", "Event participation", "Community visibility", "Long-term nonprofit partnerships"],
      serviceAreas: ["Grove Park", "Atlanta, GA", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Community", "Health", "Youth"],
      contributionTypes: ["Event hosting", "Sponsorship dollars", "Product donation"],
      partnershipTypes: ["Event sponsorship", "Event activation", "Hosted event", "Fundraising"],
      offerTypes: ["Event activation", "Professional services", "Corporate sponsorship"],
      productsServices: "Holistic healing and day spa services, massage, Reiki, meditation/yoga instruction, wellness workshops, and community wellness activation.",
      averagePriceRange: "$25-$150",
      minimumOrderRequirement: 300,
      minimumCapacity: 30,
      maximumCapacity: 180,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 15,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business/site, but the business is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "Casa de Luz publicly describes itself as a holistic healing center and day spa operating from Grove Park near Westside Reservoir Park, making it a wellness/community impact fit.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus official business website; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Casa%20de%20Luz%20Grove%20Park%20Atlanta%20GA",
      sourceUrl: "https://casadeluzatl.com/",
    },
    {
      id: "biz-kenekt-cooperative",
      name: "The Ke'nekt Cooperative (Potential Lead)",
      website: "https://www.thekenekt.com/",
      socialLinks: "",
      contactName: "Outreach lead to confirm",
      email: "events@thekenekt.com",
      phone: "404-748-1149",
      category: "Services",
      businessGoals: ["Community visibility", "Content opportunities", "Local press", "Long-term nonprofit partnerships"],
      serviceAreas: ["Atlanta, GA", "Southwest Atlanta", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Community", "Arts", "Workforce development"],
      contributionTypes: ["Sponsorship dollars", "Event hosting", "Product donation"],
      partnershipTypes: ["Event sponsorship", "Event activation", "Hosted event", "Fundraising"],
      offerTypes: ["Professional services", "Event activation", "Corporate sponsorship"],
      productsServices: "Community third-space programming, entrepreneur/community events, marketplace activation, content opportunities, and small-business network support.",
      averagePriceRange: "$500-$2,500",
      minimumOrderRequirement: 500,
      minimumCapacity: 40,
      maximumCapacity: 200,
      idealEventSize: 120,
      campaignCap: 1,
      activeCampaigns: 0,
      estimatedUnitContribution: 20,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["In person"],
      leadTimeDays: 21,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business/community space, but it is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "The Ke'nekt Cooperative is publicly listed as a Black-owned community third space/cafe/coworking space at 1492 Ralph David Abernathy Blvd SW, with programming around local businesses and community wealth.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus official business website; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=The%20Ke%27nekt%20Cooperative%201492%20Ralph%20David%20Abernathy%20Blvd%20SW%20Atlanta%20GA%2030310",
      sourceUrl: "https://www.thekenekt.com/",
    },
    {
      id: "biz-bankhead-seafood",
      name: "Bankhead Seafood (Potential Lead)",
      website: "https://www.bankheadseafood.com/",
      socialLinks: "",
      contactName: "Outreach lead to confirm",
      email: "",
      phone: "404-254-1047",
      category: "Food and beverage",
      businessGoals: ["Foot traffic", "Community visibility", "Brand awareness", "Local press"],
      serviceAreas: ["Grove Park", "Atlanta, GA", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Community", "Food access", "Youth"],
      contributionTypes: ["Percent of sales", "Event hosting", "Product donation"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Hosted event", "Event activation"],
      offerTypes: ["Food & beverage", "Event activation"],
      productsServices: "Seafood restaurant fundraiser day, community food activation, catering, and local event support.",
      averagePriceRange: "$12-$30",
      minimumOrderRequirement: 500,
      minimumCapacity: 50,
      maximumCapacity: 260,
      idealEventSize: 150,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business listing, but the business is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "Public listings place Bankhead Seafood at 1651 Donald Lee Hollowell Pkwy NW. Strong Grove Park food and local visibility fit for a fundraiser or community event activation.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus public restaurant listings; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bankhead%20Seafood%201651%20Donald%20Lee%20Hollowell%20Pkwy%20NW%20Atlanta%20GA%2030318",
      sourceUrl: "https://www.theinfatuation.com/atlanta/reviews/bankheadseafood",
    },
    {
      id: "biz-billee-redd-hospitality",
      name: "Billee Redd Hospitality (Potential Lead)",
      website: "https://billeereddhospitality.com/",
      socialLinks: "Instagram: @where.is.billeeredd",
      contactName: "Outreach lead to confirm",
      email: "hello@billeeredd.com",
      phone: "855-324-5533",
      category: "Services",
      businessGoals: ["Community visibility", "Event participation", "Content opportunities", "Long-term nonprofit partnerships"],
      serviceAreas: ["Grove Park", "Atlanta, GA", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Community", "Arts", "Workforce development"],
      contributionTypes: ["Event hosting", "Sponsorship dollars", "Product donation"],
      partnershipTypes: ["Event sponsorship", "Event activation", "Hosted event", "Fundraising"],
      offerTypes: ["Event activation", "Professional services", "Corporate sponsorship"],
      productsServices: "Mobile hospitality, craft beverage service, vendor/community event production, pop-up experiences, and market activation.",
      averagePriceRange: "$500-$3,000",
      minimumOrderRequirement: 500,
      minimumCapacity: 50,
      maximumCapacity: 300,
      idealEventSize: 150,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 20,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["In person"],
      leadTimeDays: 21,
      orgTypesSupported: ["501(c)(3) nonprofit", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business/event partner record, but the business is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "Public event pages connect Billee Redd Hospitality to Farmers Market at the Grove and Juneteenth at the Grove, making it a strong event activation and local-business ecosystem fit.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus public event/business listings; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Billee%20Redd%20Hospitality%202390%20Donald%20Lee%20Hollowell%20Pkwy%20NW%20Atlanta%20GA%2030318",
      sourceUrl: "https://farmersmarketatthegrove.com/",
    },
    {
      id: "biz-glaciers-italian-ice",
      name: "Glaciers Italian Ice (Potential Lead)",
      website: "https://www.glaciersice.org/",
      socialLinks: "",
      contactName: "Outreach lead to confirm",
      email: "info@glaciersice.org",
      phone: "404-549-9600",
      category: "Food and beverage",
      businessGoals: ["Community visibility", "CSR/community impact", "Event participation", "Brand awareness"],
      serviceAreas: ["Atlanta, GA", "Southwest Atlanta", "Westside Atlanta"],
      fulfillmentScope: "Local",
      causeAreas: ["Youth", "Community", "Education"],
      contributionTypes: ["Product donation", "Percent of sales", "Event hosting"],
      partnershipTypes: ["Fundraising", "Event activation", "Product donation", "Hosted event"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Event activation"],
      productsServices: "Italian ice pop-ups, youth entrepreneurship tie-in, dessert fundraiser, product donation, and community event activation.",
      averagePriceRange: "$5-$12",
      minimumOrderRequirement: 250,
      minimumCapacity: 40,
      maximumCapacity: 220,
      idealEventSize: 125,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 8,
      availableFrom: "2026-10-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "Potential lead for Grove Park outreach. This is a real public business/program record, but the business is not signed up with Raise Local yet and must confirm interest before any introduction.",
      rating: null,
      reviewNote: "Public listings show Glaciers Italian Ice in Atlanta with youth entrepreneurship/community programming, making it a strong youth and community activation alternate lead.",
      unavailable: false,
      status: "potential_lead",
      qualityStatus: "potential_lead",
      leadSource: "Public Google/Maps lookup plus official business website/public listings; not registered in Raise Local yet",
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Glaciers%20Italian%20Ice%201996%20Sylvan%20Rd%20SW%20Atlanta%20GA%2030310",
      sourceUrl: "https://www.glaciersice.org/book",
    },
    {
      id: "biz-sofia-grace",
      name: "Sofia & Grace",
      website: "https://sofiaandgrace.com/",
      socialLinks: "Instagram: @sofiaandgrace",
      contactName: "Shalonda Vasquez",
      email: "together@SofiaAndGrace.com",
      phone: "718-450-8034",
      category: "Food and beverage",
      businessGoals: ["Foot traffic", "Brand awareness", "Social media exposure", "Long-term nonprofit partnerships"],
      serviceAreas: ["Brooklyn", "Manhattan"],
      fulfillmentScope: "Local",
      causeAreas: ["Youth", "Food access", "Education"],
      contributionTypes: ["Product donation", "Percent of sales"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting"],
      productsServices: "Cookie boxes, dessert trays, seasonal fundraiser bundles, and pickup campaigns.",
      averagePriceRange: "$24-$48",
      minimumOrderRequirement: 300,
      minimumCapacity: 30,
      maximumCapacity: 180,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-09-10",
      availableTo: "2026-11-30",
      fulfillmentOptions: ["Pickup", "Delivery"],
      leadTimeDays: 10,
      orgTypesSupported: ["School / PTA", "501(c)(3) nonprofit"],
      notes: "Backup demo business. Public records identify Sofia & Grace Cookie Company as a Brooklyn bakery/cookie company; confirm current campaign participation before introduction.",
      rating: 4.6,
      reviewNote: "Warm brand fit for school and youth campaigns.",
      unavailable: false,
      status: "ready",
    },
  ],
  matches: [],
  notifications: [],
};

// Keep rehearsal records isolated from live account data while preserving the
// named presentation records in the demo workspace.
const DEMO_REQUEST_IDS = new Set(["request-grove-park", "request-young-excellence"]);
const DEMO_BUSINESS_IDS = new Set(["business-fe9b3739-59c6-411d-b1df-c8222bf888ca", "biz-paco-tacos-atl", "biz-casa-de-luz", "biz-kenekt-cooperative", "biz-bankhead-seafood", "biz-billee-redd-hospitality", "biz-glaciers-italian-ice", "biz-sofia-grace"]);

function isMockEmail(email) {
  return /\.example$/i.test(String(email || "").trim());
}

function demoSeedData() {
  return {
    campaignRequests: DEMO_DATA.campaignRequests.filter((record) => DEMO_REQUEST_IDS.has(record.id)),
    businesses: DEMO_DATA.businesses.filter((record) => DEMO_BUSINESS_IDS.has(record.id)),
    matches: [],
    notifications: [],
    comments: [],
  };
}

export function loadData({ includeDemo = false } = {}) {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) {
    return includeDemo
      ? structuredClone(demoSeedData())
      : { campaignRequests: [], businesses: [], matches: [], notifications: [], comments: [] };
  }

  try {
    const parsed = JSON.parse(raw);
    // Upgrades old partner-type labels (see LEGACY_SUPPORT_NEEDS in
    // matching.js) on read, non-destructively, so previously saved answers
    // keep matching instead of silently failing a string-overlap comparison.
    let campaignRequests = (Array.isArray(parsed.campaignRequests) ? parsed.campaignRequests : []).map((r) => ({
        rating: null,
        reviewNote: "",
        ...r,
        supportNeeds: normalizeSupportNeeds(r.supportNeeds),
      }));
    let businesses = (Array.isArray(parsed.businesses) ? parsed.businesses : []).map((b) => ({
        ...b,
        offerTypes: normalizeSupportNeeds(b.offerTypes),
      }));
    if (!includeDemo) {
      campaignRequests = campaignRequests.filter((record) => !DEMO_REQUEST_IDS.has(record.id) && !isMockEmail(record.email));
      businesses = businesses.filter((record) => !DEMO_BUSINESS_IDS.has(record.id) && !isMockEmail(record.email));
    }
    const existingRequestIds = new Set(campaignRequests.map((record) => record.id));
    const existingBusinessIds = new Set(businesses.map((record) => record.id));
    const demo = demoSeedData();
    return {
      campaignRequests: includeDemo ? [...campaignRequests, ...demo.campaignRequests.filter((record) => !existingRequestIds.has(record.id))] : campaignRequests,
      businesses: includeDemo ? [...businesses, ...demo.businesses.filter((record) => !existingBusinessIds.has(record.id))] : businesses,
      matches: Array.isArray(parsed.matches) ? parsed.matches : [],
      notifications: Array.isArray(parsed.notifications) ? parsed.notifications : [],
      comments: Array.isArray(parsed.comments) ? parsed.comments : [],
    };
  } catch {
    return includeDemo
      ? structuredClone(demoSeedData())
      : { campaignRequests: [], businesses: [], matches: [], notifications: [], comments: [] };
  }
}

export function saveData(data) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}

export function resetDemoData() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(demoSeedData()));
  return loadData({ includeDemo: true });
}
