import { normalizeSupportNeeds } from "./matching.js";

const STORAGE_KEY = "raise_local_platform_v2";

export const DEMO_DATA = {
  campaignRequests: [
    {
      id: "request-fresh-start",
      organizationName: "Fresh Start Pantry",
      organizationType: "501(c)(3) nonprofit",
      contactName: "Maya Thompson",
      email: "maya@example.org",
      phone: "555-0198",
      website: "https://freshstartpantry.org",
      socialLinks: "Instagram: @freshstartpantry",
      classification: "501(c)(3)",
      communitiesServed: "Brooklyn families and school communities",
      mission: "Reduce weekend food insecurity for families with school-aged children.",
      audienceServed: "Families, parents, volunteers, and local donors",
      audienceSize: 850,
      campaignDescription: "Stock weekend meal bags for families during the fall school term.",
      fundingGoal: 5000,
      expectedParticipation: 120,
      minimumSize: 80,
      idealSize: 120,
      startDate: "2026-09-15",
      endDate: "2026-10-15",
      partnershipDeadline: "2026-09-10",
      causeArea: "Food access",
      businessPreference: "Food and beverage",
      preferredCategories: ["Food and beverage", "Restaurant", "Beverage"],
      eventType: "Food-based fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Percentage of sales campaign", "Product donation"],
      supportNeeds: ["Food & beverage", "Products or corporate gifting"],
      geography: "Brooklyn",
      mustHaves: "Brooklyn service area, food-based support, capacity for at least 80 orders.",
      niceToHaves: "Pickup option and a recognizable local brand.",
      priorFundraiser: "Yes - local restaurant night",
      status: "new",
    },
    {
      id: "request-art-room",
      organizationName: "PS 118 Art Room",
      organizationType: "School / PTA",
      contactName: "Jordan Lee",
      email: "jordan@example.edu",
      phone: "555-0142",
      website: "https://ps118.example.edu",
      socialLinks: "Instagram: @ps118artroom",
      classification: "School / PTA",
      communitiesServed: "Queens students, parents, teachers, and neighborhood donors",
      mission: "Expand access to creative enrichment and student art showcases.",
      audienceServed: "Students, parents, teachers, and alumni",
      audienceSize: 600,
      campaignDescription: "Raise money for after-school art supplies and student showcase materials.",
      fundingGoal: 3500,
      expectedParticipation: 90,
      minimumSize: 50,
      idealSize: 90,
      startDate: "2026-10-01",
      endDate: "2026-10-31",
      partnershipDeadline: "2026-09-24",
      causeArea: "Arts",
      businessPreference: "Retail",
      preferredCategories: ["Retail", "Local media"],
      eventType: "Product fundraiser",
      partnershipTypesNeeded: ["Fundraising", "Event sponsorship", "Product donation"],
      supportNeeds: ["Products or corporate gifting", "Corporate sponsorship"],
      geography: "Queens",
      mustHaves: "Queens service area and product or sponsorship support.",
      niceToHaves: "School-friendly business and flexible campaign dates.",
      priorFundraiser: "No",
      status: "new",
    },
  ],
  businesses: [
    {
      id: "biz-yamaas",
      name: "YAMAAS! Olive Oil",
      website: "https://yamaasoliveoil.example",
      socialLinks: "Instagram: @yamaasoliveoil",
      category: "Food and beverage",
      businessGoals: ["New customers", "Product trial", "Community visibility", "CSR/community impact"],
      serviceAreas: ["Brooklyn", "Queens", "New York"],
      fulfillmentScope: "Local",
      causeAreas: ["Food access", "Community", "Health"],
      contributionTypes: ["Product donation", "Percent of sales", "Event hosting"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Hosted event", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting", "Venue space"],
      productsServices: "Olive oil sets, tasting kits, hosted sampling events, and gift bundles.",
      averagePriceRange: "$18-$65",
      minimumOrderRequirement: 500,
      minimumCapacity: 50,
      maximumCapacity: 250,
      idealEventSize: 125,
      campaignCap: 3,
      activeCampaigns: 1,
      estimatedUnitContribution: 20,
      availableFrom: "2026-09-01",
      availableTo: "2026-12-15",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 14,
      orgTypesSupported: ["501(c)(3) nonprofit", "School / PTA", "Community organization"],
      notes: "Founding business. Strong fit for food, wellness, and community campaigns.",
      rating: 4.8,
      reviewNote: "Reliable partner for community food campaigns.",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-sofia-grace",
      name: "Sofia & Grace",
      website: "https://sofiaandgrace.example",
      socialLinks: "Instagram: @sofiaandgrace",
      category: "Food and beverage",
      businessGoals: ["Foot traffic", "Brand awareness", "Social media exposure", "Long-term nonprofit partnerships"],
      serviceAreas: ["Brooklyn", "Manhattan"],
      fulfillmentScope: "Local",
      causeAreas: ["Youth", "Food access", "Education"],
      contributionTypes: ["Product donation", "Percent of sales"],
      partnershipTypes: ["Fundraising", "Percentage of sales campaign", "Product donation"],
      offerTypes: ["Food & beverage", "Products or corporate gifting"],
      productsServices: "Cookie boxes, dessert trays, seasonal fundraiser bundles, and pickup campaigns.",
      averagePriceRange: "$24-$48",
      minimumOrderRequirement: 300,
      minimumCapacity: 30,
      maximumCapacity: 180,
      idealEventSize: 100,
      campaignCap: 2,
      activeCampaigns: 0,
      estimatedUnitContribution: 12,
      availableFrom: "2026-09-10",
      availableTo: "2026-11-30",
      fulfillmentOptions: ["Pickup", "Delivery"],
      leadTimeDays: 10,
      orgTypesSupported: ["School / PTA", "501(c)(3) nonprofit"],
      notes: "Founding business. Cookie shop interview validated appetite for local cause partnerships.",
      rating: 4.6,
      reviewNote: "Warm brand fit for school and youth campaigns.",
      unavailable: false,
      status: "ready",
    },
    {
      id: "biz-paper-porch",
      name: "Paper Porch Goods",
      website: "https://paperporchgoods.example",
      socialLinks: "Instagram: @paperporchgoods",
      category: "Retail",
      businessGoals: ["Community visibility", "Email/newsletter exposure", "Content opportunities", "Local press"],
      serviceAreas: ["Queens", "Brooklyn"],
      fulfillmentScope: "Regional",
      causeAreas: ["Arts", "Education", "Community"],
      contributionTypes: ["Percent of sales", "Sponsorship dollars"],
      partnershipTypes: ["Fundraising", "Event sponsorship", "Product donation"],
      offerTypes: ["Products or corporate gifting", "Corporate sponsorship"],
      productsServices: "Stationery bundles, classroom supply packs, raffle prizes, and sponsor dollars.",
      averagePriceRange: "$12-$40",
      minimumOrderRequirement: 250,
      minimumCapacity: 40,
      maximumCapacity: 120,
      idealEventSize: 80,
      campaignCap: 1,
      activeCampaigns: 0,
      estimatedUnitContribution: 15,
      availableFrom: "2026-09-20",
      availableTo: "2026-12-31",
      fulfillmentOptions: ["Pickup", "In person"],
      leadTimeDays: 7,
      orgTypesSupported: ["School / PTA", "Community organization", "501(c)(3) nonprofit"],
      notes: "Good fit for school, arts, and neighborhood campaigns.",
      rating: 4.2,
      reviewNote: "Strong for small product fundraisers and school campaigns.",
      unavailable: false,
      status: "ready",
    },
  ],
  matches: [],
};

export function loadData() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return structuredClone(DEMO_DATA);
  try {
    const parsed = JSON.parse(raw);
    // Partner-type labels were rewritten after the Sept 11 walkthrough (see
    // matching.js). Matching is a plain string-overlap test, so a saved
    // answer of "Products" against a new "Products or corporate gifting"
    // would just stop matching — silently, with no error and no result.
    // Upgrading on read keeps anyone who already filled the quiz working,
    // without a destructive rewrite of their stored answers.
    return {
      campaignRequests: (Array.isArray(parsed.campaignRequests) ? parsed.campaignRequests : []).map((r) => ({
        ...r,
        supportNeeds: normalizeSupportNeeds(r.supportNeeds),
      })),
      businesses: (Array.isArray(parsed.businesses) ? parsed.businesses : []).map((b) => ({
        ...b,
        offerTypes: normalizeSupportNeeds(b.offerTypes),
      })),
      matches: Array.isArray(parsed.matches) ? parsed.matches : [],
    };
  } catch {
    return structuredClone(DEMO_DATA);
  }
}

export function saveData(data) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
}

export function resetDemoData() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(DEMO_DATA));
  return loadData();
}
